### ISSUE TITLE
Framecount inconsistencies between reported TTLs and video files

### ISSUE THREAD

**Issue by nimrodlbr** [arnefmeyer/RPiCameraPlugin#9]
Hi, 

There seem to be an inconsistency between the number of reported frames in the timestamps.csv and the number of frames in the converted mp4 video file - this inconsistency persists, and is accurately reproduced, even when converting the videos format via opencv frame-by-frame. 

Have you encountered this phenomenon? 

I am having trouble syncing up the videos as the reported number of frames (and the open-ephys events file which records TTLs from the two RPis) do not match the amount of frames I end up with after conversion to mp4.

Thanks again, and sorry for the trouble.

**Comment by arnefmeyer** [comment]
There might be more video frames than TTL timestamps as the OE GUI typically stops the plugin that is recording TTL timestamps (e.g., the Rhythm FPGA plugin) before the RPi which is recording video data. You can ignore the last few video frames. However, you might want to double-check if this is also true in your case, e.g., by recording a flashing LED with the RPi camera and the LED voltage with the OE board.

**Comment by nimrodlbr** [comment]
My phenomenon is actually reversed - There are more TTLs than Frames. 

At first, it was because the quality settings were too high - I pulled them down to the level where there are no reported dropped frames at all (quality values = 19). 

Even so, some reported video frames (that appear in the OE GUI events channels as well as the timestamps.csv files on the RPis) are not a part of the h.264 video file (I checked this with MP4Box conversion and gpac inspect + a conversion of the raw h.264 video to individual JPEGs which yielded the same frame-count).  

For example - An h.264 video file with a timestamps.csv file containing 25542 frame timestamps (corresponding 25542 OE GUI TTLs) is converted to a .mp4 file and analyzed with : "gpac -i videoname.mp4 inspect"
This returns a NumFrames value of 23166, which is 2376 missing frames (almost 40 seconds of video @ 60FPS)
 
Have you encountered something like this?

**Comment by arnefmeyer** [comment]
No, I have never encountered this before. All the camera code is doing for each frame is to send a 3.3V pulse (via GPIO), writing timestamps to the csv file, and passing the frame to the [picamera](https://github.com/waveform80/picamera) video encoder for further processing. To test if this is causing dropped frames you can simply comment out the `_frame_callback(...)` method of the `VideoEncoderGPIO` class and check if you get 60 Hz for the same recording duration as above:
https://github.com/arnefmeyer/RPiCameraPlugin/blob/master/Python/rpicamera/camera.py

Alternatively, you can use the [raspivid](https://www.raspberrypi.org/documentation/usage/camera/raspicam/raspivid.md) command to record video using the RPi camera (the -t option allows you to set the duration in ms).

If this does not help then there might be a general issue with writing video frames, e.g., due to a slow SD card.

**Comment by nimrodlbr** [comment]
Thank you, 

I've tried a couple of different setups and settings - 
It seems that this issue arises when there is a high information density section of video to encode and the quality setting brings the demands from the system up to a point below the threshold for a buffering error but, as you pointed out, above the threshold for a frame to be dropped on the level of the SD bus. This results in a positive timestamp (because a negative timestamp will only arise if the problem is in the buffer) and a dropped frame, which doesn't make it into the resulting video file. 

It is not clear that this problem is due to a slow SD card as I've tried to switch cards to a fast one (Sandisk extreme pro microSD XC I V30 UHS3 A2) with no apparent improvement - what I suspect is happening is that the SD bus of the Pi itself is the bottleneck limiting the write speed and dropping the frames. 

I will try to utilize the USB port (as it is supposedly faster than the SD bus / storage controller) in the Pi and see if I can get to better quality values without frame-dropping, but for the meantime I'll compromise on quality to get clean synchronization. 

Thanks again! I'll let you know if I find a workaround :)
